name: Reusable workflow example

on:
  workflow_call:

jobs:
  build:
    name: "Build Project"
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Installing required node modules 
        run: |
          npm install -g gatsby-cli

      - name: Running Build
        run: |
          cd my-first-gatsby-site && gatsby build
