name: Reusable workflow example

on:
  workflow_call:

jobs:
  build:
    name: "Build Project"
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Running Build
        run: |
          echo "Building the project ..."
