name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy-pre-release:
    name: "Deploy pre-release"
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: "Deploying pre-release"
        run: |
          echo "Deploying project ${{ github.ref }} to environment ${{ inputs.environment }}..."
          echo "Using token ${{ secrets.token }} ..."