name: pre-release
on:
  push:
    branches:
      - "pre-release"

jobs:
  call-workflow-passing-data:
    uses: andreasfedermann/workflow-examples/.github/workflows/reusable-workflow.yml@main
    with:
      environment: staging
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
