name: Pre-Release
on:
  push:
    branches:
      - "pre-release"

jobs:
  build:
    uses: andreasfedermann/workflow-examples/.github/reusables/build.yml@main

  test:
    uses: andreasfedermann/workflow-examples/.github/reusables/test.yml@main
    needs: [build]

  compliance-test:
    uses: andreasfedermann/workflow-examples/.github/reusables/compliance-test.yml@main
    needs: [build]

  deploy:
    uses: andreasfedermann/workflow-examples/.github/reusables/deploy.yml@main
    needs: [test, compliance-test]
    with:
      environment: staging
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}