name: pre-release
on:
  push:
    branches:
      - "pre-release"

jobs:
  build:
    uses: andreasfedermann/workflow-examples/.github/workflows/build.yml@main

  test:
    uses: andreasfedermann/workflow-examples/.github/workflows/test.yml@main
    needs: [build]

  deploy:
    uses: andreasfedermann/workflow-examples/.github/workflows/deploy.yml@main
    needs: [test]
    with:
      environment: staging
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}