name: Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    uses: andreasfedermann/workflow-examples/.github/workflows/build.yml@main

  test:
    uses: andreasfedermann/workflow-examples/.github/workflows/test.yml@main
    needs: [build]

  compliance-test:
    uses: andreasfedermann/workflow-examples/.github/workflows/compliance-test.yml@main
    needs: [build]

  deploy:
    uses: andreasfedermann/workflow-examples/.github/workflows/deploy.yml@main
    needs: [test]
    with:
      environment: production
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
