name: Reusable workflow example

on:
  workflow_call:

jobs:
  test:
    name: "Run Unit Tests"
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: "Running Tests"
        run: |
          echo "Testing the project ..."
